language: dart

matrix:
  include:
    - os: linux
      dart_task:
      - test: --platform vm
      - test: --platform chrome
    - os: osx
      dart_task:
      - test: --platform vm
      - test: --platform chrome
    - os: windows
      dart_task:
      - test: --platform vm
      - test: --platform chrome
    - os: linux
      dart_task:
      - dartanalyze
      - dartfmt
